# Generated by Django 4.0.4 on 2022-08-17 06:40

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expired',
            field=creditcards.models.CardExpiryField(default='12/22'),
        ),
    ]
